/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#09090b",
        scaffold: "#0c0c0f",
        surface: "#13131a",
        "surface-hover": "#18181f",
        "surface-bright": "#39393b",
        "surface-container": "#201f22",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-container-low": "#1c1b1d",
        "surface-container-lowest": "#0e0e10",
        "surface-dim": "#131315",
        border: "#1e1e26",
        "border-hover": "#2a2a35",
        primary: {
          DEFAULT: "#3b82f6",
          hover: "#2563eb",
          container: "#4d8eff",
          on: "#002e6a",
        },
        secondary: {
          DEFAULT: "#c6c6cf",
          container: "#45464e",
          on: "#2f3037",
        },
        tertiary: {
          DEFAULT: "#4ae176",
          container: "#00a74b",
          on: "#003915",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
          on: "#690005",
        },
        "text-muted": "#71717a",
        "text-dim": "#52525b",
        "on-surface": "#e5e1e4",
        "on-background": "#e5e1e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Geist", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "4px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        gutter: "20px",
        "container-max": "1152px",
      },
    },
  },
  plugins: [],
}
